# ./docker-compose.yml

version: '3.4'

services:
  model:
    build:
      context: .
      network: brDown
    volumes:
      - ./web:/app/
    ports:
     - "8102:5000"
    stdin_open: true
    tty: true

volumes:
  volumeDB:

networks:
  brDown:
    external: true
